import {Inter} from 'next/font/google';
import './styles/globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import Head from 'next/head';
import './styles/fontawesome-free-6.1.1-web/css/all.css';

const inter = Inter({subsets: ['latin']});

export const metadata = {
	// title: 'Create Next App',
	description: 'Generated by create next app',
	link: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css',
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
			<Head>
				<title>My page title</title>
				<meta property="og:title" content="My page title" key="title" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
				></link>
			</Head>
			<body className={inter.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
